# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tinder' do
    use_frameworks!

    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Core'
    pod 'AKMaskField'
    pod 'PKHUD', '5.1.0'
    pod 'Koloda'
    pod 'IQKeyboardManagerSwift'
    pod 'ObjectMapper'
    pod 'Firebase/Storage'
    pod 'SDWebImage'
    pod 'GrowingTextView', '0.5'
    pod 'Firebase/Messaging'
    
    pod 'FacebookSDK'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
